name: Fly Deploy
on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use (e.g. v1.2.3)'
        required: true
jobs:
  deploy:
    environment: Fly
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Initial static JSON schema submodule
        run: git submodule update --init ./src/Helldivers-2-Models/json

      - name: Set Version
        id: set_version
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            VERSION="${{ github.event.inputs.version }}"
          else
            VERSION="${GITHUB_REF##*/}"
          fi
          
          VERSION_WITHOUT_V="${VERSION#v}"
          
          echo "VERSION=$VERSION"
          echo "VERSION_WITHOUT_V=$VERSION_WITHOUT_V"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "version-without-v=$VERSION_WITHOUT_V" >> $GITHUB_OUTPUT

      - run: flyctl deploy --remote-only --build-arg VERSION=${{ steps.set_version.outputs.version-without-v }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
